name: Teste

on: [push, workflow_dispatch]
jobs:
    teste:
        uses: LucasRius/lrios-ci-complete/.github/workflows/ci.yml@main
        permissions:
            contents: write
        with:
            service-name: teste-kotlin
            target-env: prd
            language: 'kotlin'
            build_tool: 'gradle'
            lint_bypass: true
            cache_path: |
                **/*.jar
                **/*.tgz
        secrets: inherit
            
          

