name: Teste

on: push
jobs:
    teste:
        uses: LucasRius/lrios-ci-complete/.github/workflows/ci-lint-kotlin.yml@main
        with:
            # language: 'kotlin'
            build_tool: 'gradle'